In [ ]:
from google.colab import drive

drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
import pandas as pd

file_path = '/content/gdrive/My Drive/Books.json'

df = pd.read_json(file_path, lines=True)

df.keys()

Index(['reviewerID', 'asin', 'reviewerName', 'helpful', 'reviewText',
       'overall', 'summary', 'unixReviewTime', 'reviewTime'],
      dtype='object')

In [ ]:
df.iloc[:5]

reviewerID        asin             reviewerName helpful  \
0   A1E5ZR1Z4OQJG  1495329321  Pure Jonel "Pure Jonel"  [0, 0]   
1  A30PZPI6FPH0A7  0399157565               Jackmollie  [0, 0]   
2  A1GQ2UI5BKCCRD  0984528105              Gail Hodges  [0, 0]   
3  A2DF4LQQI6KSQ2  0804139024                     Olga  [0, 0]   
4   A1UAMAWY966P2  0765317583        Nadyne M Ichimura  [0, 0]   

                                          reviewText  overall  \
0  Da Silva takes the divine by storm with this u...        4   
1  For me personally it's the most disappointing ...        2   
2  Very simple book, but leaves you feeling good....        4   
3  I read a library copy of this exceptionally we...        5   
4  With the government knowing this could happen ...        5   

                        summary  unixReviewTime   reviewTime  
0        An amazing first novel      1396137600  03 30, 2014  
1                  disappointed      1400112000  05 15, 2014  
2                     Good book      1401235200  05 28, 2014  
3  Science Fiction at its best!      1396483200   04 3, 2014  
4               Excellent story      1397001600   04 9, 2014

In [ ]:
from collections import Counter

counter = Counter(df['overall'])

sorted_counter = sorted(counter.items())

sorted_counter


[(1, 21), (2, 41), (3, 103), (4, 226), (5, 609)]

In [ ]:
text_ex = []
overall_ex = []

for text, score in zip(df['reviewText'], df['overall']):
  text_ex.append(text)
  overall_ex.append(score)

data_ex = {
    'reviewText': text_ex,
    'overall': overall_ex
}

data_frame = pd.DataFrame(data_ex)


data_frame


reviewText  overall
0    Da Silva takes the divine by storm with this u...        4
1    For me personally it's the most disappointing ...        2
2    Very simple book, but leaves you feeling good....        4
3    I read a library copy of this exceptionally we...        5
4    With the government knowing this could happen ...        5
..                                                 ...      ...
995  I thoroughly enjoyed this book. I've read the ...        5
996  I was impressed with not only the characters o...        5
997  I like the characters.  I had read the short s...        5
998  She got way she wanted,but can she pick the ri...        5
999  All these twists, turns and discoveries. There...        5

[1000 rows x 2 columns]

In [ ]:
reviews = [df['reviewText'], df['overall']]

data_frame = pd.DataFrame(reviews)

data = data_frame.T

data

reviewText overall
0    Da Silva takes the divine by storm with this u...       4
1    For me personally it's the most disappointing ...       2
2    Very simple book, but leaves you feeling good....       4
3    I read a library copy of this exceptionally we...       5
4    With the government knowing this could happen ...       5
..                                                 ...     ...
995  I thoroughly enjoyed this book. I've read the ...       5
996  I was impressed with not only the characters o...       5
997  I like the characters.  I had read the short s...       5
998  She got way she wanted,but can she pick the ri...       5
999  All these twists, turns and discoveries. There...       5

[1000 rows x 2 columns]

In [ ]:
data.iloc[5]

reviewText    Love the book, great story line, keeps you ent...
overall                                                       4
Name: 5, dtype: object

In [ ]:
class Sentiment:
  NEGATIVE = 'NEGATIVE'
  NEUTRAL = 'NEUTRAL'
  POSITIVE = 'POSITIVE'


class Review:
  def __init__(self, text, score):
    self.text = text
    self.score = score

  def __repr__(self) -> str:
    return f'{self.text}, {self.score}'

  def get_sentiment(self):
    if self.score <= 2:
      return Sentiment.NEGATIVE
    elif self.score == 3:
      return Sentiment.NEUTRAL
    else:
      return Sentiment.POSITIVE

In [ ]:
test_data = []

for text, score in zip(df['reviewText'], df['overall']):
  test_data.append(Review(text, score))

test_data[1].get_sentiment()

'NEGATIVE'

In [ ]:
len(data)

1000

In [ ]:
from sklearn.model_selection import train_test_split

training, test = train_test_split(data, test_size=0.33, random_state=42)

training.shape, test.shape

((670, 2), (330, 2))

In [ ]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(test_data, test_size=0.33, random_state=42)

len(train), len(test)

(670, 330)

In [ ]:
train[0].get_sentiment()

'POSITIVE'

In [ ]:
train_x = [x.text for x in train]
train_y = [x.get_sentiment() for x in train]

test_x = [x.text for x in test]
test_y = [x.get_sentiment() for x in test]

train_x[0]
train_y[0]

'POSITIVE'

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
vectorizer.fit_transform(train_x)

<670x7372 sparse matrix of type '<class 'numpy.int64'>'
	with 41455 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
train_x_vectors = vectorizer.fit_transform(train_x)

test_x_vectors = vectorizer.transform(test_x)

train_x[0]
train_x_vectors[0].toarray()


array([[0, 0, 0, ..., 0, 0, 0]])

### Classification

In [ ]:
from sklearn import svm

clf_svm = svm.SVC(kernel='linear')

clf_svm.fit(train_x_vectors, train_y, )

test_x[0]

clf_svm.predict(test_x_vectors[0])


array(['POSITIVE'], dtype='<U8')

Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier

clf_dec = DecisionTreeClassifier()
clf_dec.fit(train_x_vectors, train_y)
clf_dec.predict(test_x_vectors[0])

array(['POSITIVE'], dtype='<U8')

Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB

clf_gnb = DecisionTreeClassifier()
clf_gnb.fit(train_x_vectors, train_y)
clf_gnb.predict(test_x_vectors[0])

array(['POSITIVE'], dtype='<U8')

Logistic

In [ ]:
from sklearn.linear_model import LogisticRegression

clf_log = LogisticRegression()
clf_log.fit(train_x_vectors, train_y)
clf_log.predict(test_x_vectors[0])

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array(['POSITIVE'], dtype='<U8')

## Evaluation

mean accuracy

In [ ]:
clf_svm.score(test_x_vectors, test_y)

0.8242424242424242

In [ ]:
clf_dec.score(test_x_vectors, test_y)

0.7515151515151515

In [ ]:
clf_gnb.score(test_x_vectors, test_y)

0.7424242424242424

In [ ]:
clf_log.score(test_x_vectors, test_y)

0.8303030303030303

f1_scores

In [ ]:
from sklearn.metrics import f1_score

f1_score_svm = f1_score(test_y, clf_svm.predict(test_x_vectors), average=None, labels=[Sentiment.POSITIVE, Sentiment.NEUTRAL, Sentiment.NEGATIVE])
f1_score_svm

array([0.91319444, 0.21052632, 0.22222222])

In [ ]:
f1_score_dec = f1_score(test_y, clf_dec.predict(test_x_vectors), average=None, labels=[Sentiment.POSITIVE, Sentiment.NEUTRAL, Sentiment.NEGATIVE])
f1_score_dec

array([0.86071429, 0.17391304, 0.06451613])

In [ ]:
f1_score_gnb = f1_score(test_y, clf_gnb.predict(test_x_vectors), average=None, labels=[Sentiment.POSITIVE, Sentiment.NEUTRAL, Sentiment.NEGATIVE])
f1_score_gnb

array([0.85968028, 0.09677419, 0.        ])

In [ ]:
f1_score_log = f1_score(test_y, clf_log.predict(test_x_vectors), average=None, labels=[Sentiment.POSITIVE, Sentiment.NEUTRAL, Sentiment.NEGATIVE])
f1_score_log

array([0.91370558, 0.12244898, 0.1       ])